version: '3.9'
services:
  asterisk:
    image: asterisk
    build:
      context: .
      dockerfile: asterisk.Dockerfile
    volumes:
      - asterisk-volume-lib:/var/lib
      - asterisk-volume-var:/var
    ports: 
      - "5060:5060"
      - "30000-30100:30000-30100"
    expose:
      - 5060
      - 30000-30100
    networks:
      voip:
        ipv4_address: 172.20.0.2

  mysql:
    image: mysql:5.7
    volumes:
      - mysql-volume:/var/lib/mysql
    networks:
      voip:
        ipv4_address: 172.20.0.3
    environment:
      MYSQL_ROOT_PASSWORD: root

  kamailio:
    image: kamailio
    build:
      context: .
      dockerfile: kamailio.Dockerfile
    ports: 
      - "80:80"
      - "443:443"
    networks:
      voip:
        ipv4_address: 172.20.0.4
    depends_on:
      - asterisk
      - mysql
    expose:
      - 80
      - 443

  phone:
    image: phone
    build:
      context: .
      dockerfile: sip-phone.Dockerfile
    ports: 
      - "8080:8080"
    networks:
      voip:
        ipv4_address: 172.20.0.5
    depends_on:
      - kamailio
    expose:
      - 8080

volumes:
  asterisk-volume-lib:
  asterisk-volume-var:
  mysql-volume:

networks:
  voip:
    ipam:
      config:
        - subnet: 172.20.0.0/16